url: https://2000-class-association.github.io/website
title: 2000 Class Association
subtitle: Probably the best entry-level family performance asymmetric sailing dinghy in the world!
keywords:
- Laser 2000
- RS 2000
- sailing
- dinghy
- asymmetric
- association
- club
