url: https://beta.2000class.org
title: 2000 Class Association
subtitle: Probably the best entry-level family performance asymmetric sailing dinghy in the world!
description: >
  The 2000 Class Association is the official association for the 2000 sailing 
  dinghy. The 2000, previously known as the Laser 2000, is an entry-level 
  performance assymmetric sailing dinghy. The boat is sailed by serious racers
  and families alike.
author: 2000 Class Association
established: 1999
licence: https://creativecommons.org/licenses/by/4.0/
lang: en_GB

collections:
  events:
    output: true

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - "*.ps1"