name: Build GitHub Pages website
on: 
  push:
    branches:    
    - master 
  schedule:
  - cron: '0 2 * * *'  # At 0200hrs UTC every day

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        ref: master
    - name: Environment info
      run: printenv
    - name: Run Jekyll
      uses: faph/action-jekyll@v0.1
