name: Build GitHub Pages website
on: 
  push:
    branches:    
    - master 
  schedule:
  - cron: '0 2 * * *'  # At 0200hrs UTC every day

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - name: Environment info
      run: printenv
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        ref: master
    - name: Run Jekyll
      uses: docker://faph/action-jekyll-2
    - name: Configure git
      run: |
        git config committer.email "noreply@github.com"
        git config committer.name "GitHub"
        git config author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config author.name "${GITHUB_ACTOR}"
    - name: Commit and push build dir
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        credentials=$(echo -n "${GITHUB_ACTOR}:${GITHUB_TOKEN}" | base64)
        authheader="Authorization: Basic ${credentials}"
        pushd _site
        ls -al
        git init
        git add .
        #git commit --message "Publishing website" --verbose
        popd
        
