name: Build GitHub Pages website
on: 
  push:
    branches:    
    - master 
  schedule:
  - cron: '0 2 * * *'  # At 0200hrs UTC every day

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - name: Environment info
      run: |
        whoami
        printenv
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        ref: master
    - name: Run Jekyll container manually
      run: |
        /usr/bin/docker run \
        --rm \
        -e "DEBUG=true" \
        --volume "/home/runner/work/2000-class-association.github.io/2000-class-association.github.io":"/srv/jekyll" \
        jekyll/jekyll:3.8.5 jekyll build --future --verbose
    - name: Run Jekyll
      uses: faph/action-jekyll@v0.1
