name: Build GitHub Pages website
on: 
  push:
    branches:    
    - master 
  schedule:
  - cron: '0 2 * * *'  # At 0200hrs UTC every day

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - name: Environment info
      run: printenv
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        ref: master
    - name: Run Jekyll
      uses: docker://ruby:2.3.4
      with:
        entrypoint: "bundle install && bundle exec jekyll build --verbose"
    - name: Run Jekyll 2
      uses: faph/action-jekyll-2/build@master
