name: Validation
on: 
  push:
    branches:    
    - master 
  
jobs:
  validation:
    name: HTML5 validation
    runs-on: ubuntu-latest
    services:
      jekyll:
        image: docker://jekyll/jekyll:3.8.5
        volumes:
        - $GITHUB_WORKSPACE:/srv/jekyll
    steps:
    - name: Environment info
      run: printenv
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        ref: master
    - name: Run Jekyll
      uses: docker://faph/action-jekyll-2:1.5
    - name: HTML5 validation
      uses: docker://validator/validator@sha256:7f4f336d3df5907751848b53aceb347d160384b9840a2d87b5b87b3836557b2b
      with:
        entrypoint: /vnu-runtime-image/bin/vnu
        args: --verbose --skip-non-html _site
    - name: CSS validation
      uses: docker://validator/validator@sha256:7f4f336d3df5907751848b53aceb347d160384b9840a2d87b5b87b3836557b2b
      with:
        entrypoint: /vnu-runtime-image/bin/vnu
        args: --verbose --css _site/assets/css/styles.css
